[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:8080 --workers 1 --timeout 120'
